fix: remove line breaks in base64 encoding
This PR fixes an issue I encountered trying to generate the manifest to
apply the new GCP provider. I received an error like
```
Error: accumulating resources: accumulating resources from 'provider-components-gcp.yaml': YAML file [provider-components-gcp.yaml] encounters a format error.
error converting YAML to JSON: yaml: line 5: could not find expected ':'

```
when running generate.sh. Removing line breaks seems to fix this behavior.

Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>